/** NPC portrait URL mapping (only NPCs with dedicated portraits) */
export const NPC_PORTRAITS: Record<string, string> = {
  // CORE 5
  NPC_HARLUN: '/npc-portraits/harulun_boss.webp',
  NPC_EDRIC_VEIL: '/npc-portraits/edric_veil.webp',
  NPC_MAIREL: '/npc-portraits/mairel_dan.webp',
  NPC_LORD_VANCE: '/npc-portraits/lord_vance.webp',
  NPC_RAT_KING: '/npc-portraits/rat_king.webp',
  // SUB 12
  NPC_TOBREN: '/npc-portraits/tobren.webp',
  NPC_MOON_SEA: '/npc-portraits/laira_kestel.webp',
  NPC_MIRELA: '/npc-portraits/mirela.webp',
  NPC_RENNICK: '/npc-portraits/rennick.webp',
  NPC_CAPTAIN_BREN: '/npc-portraits/captain_bren.webp',
  NPC_ROSA: '/npc-portraits/rosa.webp',
  NPC_INFO_BROKER: '/npc-portraits/shadow_broker.webp',
  NPC_GUARD_CAPTAIN: '/npc-portraits/captain_bellon.webp',
  NPC_OWEN_KEEPER: '/npc-portraits/owen.webp',
  NPC_SERA_DOCKS: '/npc-portraits/sera.webp',
  NPC_DAME_ISOLDE: '/npc-portraits/dame_isolde.webp',
  NPC_GUARD_FELIX: '/npc-portraits/felix.webp',
  // 퀘스트 NPC
  NPC_RONEN: '/npc-portraits/ronen.webp',
  // BACKGROUND NPC (프롤로그/시장 조연)
  NPC_BG_FRUIT_VENDOR: '/npc-portraits/fruit_vendor.webp',
  NPC_BG_SHOE_SHINE: '/npc-portraits/shoe_shine.webp',
  NPC_BG_STREET_KID: '/npc-portraits/street_kid.webp',
  NPC_BG_DRUNK: '/npc-portraits/drunk.webp',
  NPC_BG_HERB_CRONE: '/npc-portraits/herb_crone.webp',
  NPC_BG_BARMAID: '/npc-portraits/barmaid.webp',
  NPC_BG_DOCKER: '/npc-portraits/docker.webp',
  NPC_BG_BEGGAR: '/npc-portraits/beggar.webp',
  NPC_BG_CUSTOMS: '/npc-portraits/customs.webp',
  NPC_BG_FISHMONGER: '/npc-portraits/fishmonger.webp',
  NPC_BG_VAGRANT: '/npc-portraits/vagrant.webp',
  // 선술집 상주 BG 6명 — 사랑방 개방 후속 (arch/68 부록 G, 2026-07-12)
  NPC_BG_BARD: '/npc-portraits/tavern_bard.webp',
  NPC_BG_COOK: '/npc-portraits/tavern_cook.webp',
  NPC_BG_CAPTAIN_OLD: '/npc-portraits/harbor_captain_pipe.webp',
  NPC_BG_ARMORER: '/npc-portraits/veteran_swordsmith.webp',
  NPC_BG_ANTIQUE_DEALER: '/npc-portraits/old_artificer.webp',
  NPC_BG_WAREHOUSE_GUARD: '/npc-portraits/milo.webp',
  // ── star_sand_v1 (극야해안 별고래의 무덤) ──
  NPC_SS_IREN: '/npc-portraits/star_sand_v1/warm_winter_woman.webp',
  NPC_SS_LUOR: '/npc-portraits/star_sand_v1/mystic_night_priestess.webp',
  NPC_SS_SAEL: '/npc-portraits/star_sand_v1/winter_navigator_mechanism.webp',
  NPC_SS_MAREK: '/npc-portraits/star_sand_v1/lonely_frozen_warrior.webp',
  NPC_SS_KAILUN: '/npc-portraits/star_sand_v1/dark_market_mage.webp',
  NPC_SS_NAHAT: '/npc-portraits/star_sand_v1/starlit_sea_guardian.webp',
  NPC_SS_BRAN: '/npc-portraits/star_sand_v1/dark_harbor_warrior.webp',
  // SUB 11
  NPC_SS_SEFI: '/npc-portraits/star_sand_v1/young_pilgrim_guide.webp',
  NPC_SS_ODRIN: '/npc-portraits/star_sand_v1/observatory_scribe.webp',
  NPC_SS_HELUN: '/npc-portraits/star_sand_v1/old_undertaker_lodger.webp',
  NPC_SS_RIVA: '/npc-portraits/star_sand_v1/black_ice_courier.webp',
  NPC_SS_ABAS: '/npc-portraits/star_sand_v1/whaleoil_lamp_artisan.webp',
  NPC_SS_MIREN: '/npc-portraits/star_sand_v1/afflicted_ex_miner.webp',
  NPC_SS_TOBA: '/npc-portraits/star_sand_v1/harbor_route_broker.webp',
  NPC_SS_KASIEN: '/npc-portraits/star_sand_v1/coast_hunter_elder.webp',
  NPC_SS_YURMA: '/npc-portraits/star_sand_v1/armed_pilgrim_seeker.webp',
  NPC_SS_PENA: '/npc-portraits/star_sand_v1/heart_pool_licensor.webp',
  NPC_SS_ED: '/npc-portraits/star_sand_v1/wandering_name_scribe.webp',
};
